# Generated by Django 5.1 on 2024-08-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField()),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('zipcode', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
