# Generated by Django 5.1 on 2024-08-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(default='2320', max_length=300),
            preserve_default=False,
        ),
    ]
